#!/bin/bash
# This is a script which makes c source file to executable file
obj="$(echo "$1" | awk -F '.' '{print $1}')"
if [ -n "$1" ]
then
    gcc "$1" -o "$obj" -Wall && "./$obj" # -F fs:Use '.' for the input field separator
else
    echo "usage: cout C source(e.g cout test.c)"
    exit 127
fi
exit